### ISSUE TITLE
FAQ module - Accordion on storefront does not work

### ISSUE THREAD

**Issue by bdenham** [commerce-docs/pagebuilder-examples#7]
When you display the FAQ content type on the storefront, the accordion does not collapse or expand. It is always expanded.

### Steps to reproduce

In Admin:

1. Go to a CMS page. Add a "FAQ" element to the page.
2. Open the form editor and enter text for the question and answer.
3. Save the editor changes.
4. Save the page.
5. Open the page on the storefront.
6. Observe that the accordion does not collapse. It stays expanded.

**Expected result:** 
The accordion should expand and collapse when clicked.

**Actual result:** 
The accordion stays expanded and does not collapse.

**Comment by zanilee** [comment]
Hi, @bdenham !
By default,  [accordions always keep one section open](https://jqueryui.com/accordion/#default). 

To allow for all sections to be collapsible, set the [collapsible option to true](http://api.jqueryui.com/accordion/#option-collapsible) in `PageBuilderFaq/view/base/web/js/content-type/faq/appearance/default/widget.js`. This way you'll be able to lick on the currently open section to collapse its content pane:
```
element.accordion({
    collapsible: true
});
```
Also, you can make [multiple panels to be able to be expanded at the same time](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.html#collaps_multi) by adding the `multipleCollapsible: true` option to the accordion. 
Together with the `collapsible: true` option it will make the following: multiple panels can be expanded at the same time. All panes can be expanded/collapsed on click:
```
element.accordion({
    collapsible: true,
    multipleCollapsible: true
});
```

**Comment by bdenham** [comment]
Excellent info. I’ll make the adjustments. Thanks, Olga!
