### ISSUE TITLE
PageBuilderGrid Example not Working

### ISSUE THREAD

**Issue by rossmc** [commerce-docs/pagebuilder-examples#8]
Just to let you know when I installed the PageBuilderGrid Example, it does not work on the admin panel as expected.

When you add a grid, it appears differently from the [example](https://raw.githubusercontent.com/magento-devdocs/pagebuilder-examples/master/Example/PageBuilderGrid/examples/luma_homepage_admin.png).

**BEFORE ADDING IMAGES**    
![Screenshot 2019-04-03 at 12 01 51](https://user-images.githubusercontent.com/2452991/55474381-4b57f880-5611-11e9-9a1e-a41993cc4f76.png)

**AFTER ADDING IMAGES**    
![Screenshot 2019-04-03 at 13 05 55](https://user-images.githubusercontent.com/2452991/55474393-51e67000-5611-11e9-9efa-b8becba63899.png)

It appears correctly on the FE.

**Magento Version**

```
"magento/page-builder-commerce": "^1.0.0",
"magento/product-enterprise-edition": "2.3.0",
```

**Comment by davemacaulay** [comment]
This looks like an issue with static asset generation, could you try rebuilding your static assets?

**Comment by rossmc** [comment]
Thanks @davemacaulay that was it :)

It's an awesome tool btw
